class program {
  static String name = "";
  static String OrginLang = "fa";
  static String TargetLang = "en";
  static dynamic DataEssential;
  static dynamic DataTerms;

  static List<Map<String, dynamic>> WordsList = [
    {
      "fa": "کلمات ضروری",
      "en": "Essential Words",
      "ar": "الكلمات الأساسية",
      "tr": "Temel Kelimeler",
      "ru": "Основные слова",
      "fr": "Mots essentiels",
      "zh": "基础词汇",
      "ja": "基本的な単語",
      "es": "Palabras esenciales",
      "de": "Wesentliche Wörter",
    },
    {
      "fa": "مکان های توریستی",
      "en": "Tourist Places",
      "ar": "الأماكن السياحية",
      "tr": "Turistik Yerler",
      "ru": "Туристические места",
      "fr": "Lieux touristiques",
      "zh": "旅游景点",
      "ja": "観光地",
      "es": "Lugares turísticos",
      "de": "Touristische Orte",
    },
    {
      "fa": "اصطلاحات پرکاربرد",
      "en": "Common Expressions",
      "ar": "تعبيرات شائعة",
      "tr": "Yaygın İfadeler",
      "ru": "Распространённые выражения",
      "fr": "Expressions courantes",
      "zh": "常用表达",
      "ja": "よく使われる表現",
      "es": "Expresiones comunes",
      "de": "Häufig verwendete Ausdrücke",
    },
    {
      "fa": "حساب کاربری",
      "en": "User Account",
      "ar": "الحساب",
      "tr": "Kullanıcı Hesabı",
      "ru": "Учётная запись",
      "fr": "Compte utilisateur",
      "zh": "用户账户",
      "ja": "ユーザーアカウント",
      "es": "Cuenta de usuario",
      "de": "Benutzerkonto",
    },
    {
      "fa": "ترجمه آنلاین",
      "en": "Online Translation",
      "ar": "الترجمة عبر الإنترنت",
      "tr": "Çevrimiçi Çeviri",
      "ru": "Онлайн-перевод",
      "fr": "Traduction en ligne",
      "zh": "在线翻译",
      "ja": "オンライン翻訳",
      "es": "Traducción en línea",
      "de": "Online-Übersetzung",
    },
    {
      "fa": "زبان",
      "en": "Language",
      "ar": "اللغة",
      "tr": "Dil",
      "ru": "Язык",
      "fr": "Langue",
      "zh": "语言",
      "ja": "言語",
      "es": "Idioma",
      "de": "Sprache",
    },
    {
      "fa": "زبان مقصد را وارد کن",
      "en": "Enter the target language",
      "ar": "أدخل اللغة المستهدفة",
      "tr": "Hedef dili girin",
      "ru": "Введите целевой язык",
      "fr": "Entrez la langue cible",
      "zh": "输入目标语言",
      "ja": "ターゲット言語を入力してください",
      "es": "Ingresa el idioma de destino",
      "de": "Zielsprache eingeben",
    },
    {
      "fa": "رتبه بندی",
      "en": "Rating",
      "ar": "التقييم",
      "tr": "Derecelendirme",
      "ru": "Рейтинг",
      "fr": "Évaluation",
      "zh": "评分",
      "ja": "評価",
      "es": "Calificación",
      "de": "Bewertung",
    },
    {
      "fa": "نام کاربری",
      "en": "Username",
      "ar": "اسم المستخدم",
      "tr": "Kullanıcı adı",
      "ru": "Имя пользователя",
      "fr": "Nom d’utilisateur",
      "zh": "用户名",
      "ja": "ユーザー名",
      "es": "Nombre de usuario",
      "de": "Benutzername",
    },
  ];
}
